### ISSUE TITLE
app is crashin on 4.1.1

### ISSUE THREAD

**Issue by rameshvoltella** [himanshu-soni/ChatMessageView#13]
`Fatal Exception: java.lang.RuntimeException: Unable to start activity  android.view.InflateException: Binary XML file line #38: Error inflating class me.himanshusoni.chatmessageview.ChatMessageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2143)
       at android.app.ActivityThread.access$700(ActivityThread.java:140)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:4952)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
       at dalvik.system.NativeStart.main(NativeStart.java)`

but works in kitkat and above

**Comment by himanshu-soni** [comment]
@rameshvoltella fixed

**Comment by shahidghafoor00** [comment]
how did you resolved this issue ? i am getting the same crash on api 19.
 android.view.InflateException: Binary XML file line #20: Error inflating class me.himanshusoni.chatmessageview.ChatMessageView
